/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9ff',
        'surface-dim': '#d2dbe6',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ecf4ff',
        'surface-container': '#e6effa',
        'surface-container-high': '#e0e9f5',
        'surface-container-highest': '#dae3ef',
        'on-surface': '#141c25',
        'on-surface-variant': '#544245',
        'inverse-surface': '#29313a',
        'inverse-on-surface': '#e9f2fd',
        'outline': '#877275',
        'outline-variant': '#dac0c4',
        'surface-tint': '#9c3f59',
        'primary': '#9c3f59',
        'on-primary': '#ffffff',
        'primary-container': '#ff8eaa',
        'on-primary-container': '#79233e',
        'inverse-primary': '#ffb1c2',
        'secondary': '#006c52',
        'on-secondary': '#ffffff',
        'secondary-container': '#79f9ce',
        'on-secondary-container': '#007258',
        'tertiary': '#0d6683',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#73b9d9',
        'on-tertiary-container': '#004960',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9df',
        'primary-fixed-dim': '#ffb1c2',
        'on-primary-fixed': '#3f0018',
        'on-primary-fixed-variant': '#7d2742',
        'secondary-fixed': '#79f9ce',
        'secondary-fixed-dim': '#5adcb3',
        'on-secondary-fixed': '#002117',
        'on-secondary-fixed-variant': '#00513d',
        'tertiary-fixed': '#bee9ff',
        'tertiary-fixed-dim': '#8ad0f1',
        'on-tertiary-fixed': '#001f2a',
        'on-tertiary-fixed-variant': '#004d65',
        'background': '#f7f9ff',
        'on-background': '#141c25',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'container-margin': '20px',
        'card-gap': '12px',
      },
      fontFamily: {
        'quicksand': ['Quicksand', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 3s infinite ease-in-out',
        'sparkle': 'sparkle 2s infinite ease-in-out',
      },
      keyframes: {
        sparkle: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(0.8)' },
        },
      },
    },
  },
  plugins: [],
}
